### ISSUE TITLE
Add Dutch translation

### ISSUE THREAD

**Issue by opeeters** [ned14/Easyshop#26]
Hi everyone,
I worked on a Dutch translation bases on the four .pot files in the EasyShopTranslations/i18n folder. The resulting .po files I have posted here: 

http://gist.github.com/471081

I have the feeling that the .pot files I used were not very complete, since important front-of-house things like "add to cart" do not show up as translated on a website I am testing the translation on. Could someone check the completeness of the .pot files?
I had a look at the Spanish, German and French translation. Mine looks similar.

I probably misunderstood how I should translate things like "schema_available_description". I though that these lines would be used in URL's and the likes, so I translated this as "schema_beschikbaar_beschrijving". Should I have translated this to "beschikbaar" (dutch for 'available')? But then, what is the difference between "schema_available_description" and "schema_available_label"? I'd like to improve the translation. Comments are most welcome...

Cheers,
Olav

**Comment by ned14** [comment]
If something is not appearing in the translation files, then usually it is because its original text in the .pt files did not specify that the item should be translated.

The easiest thing to do here is to search all files for the thing which isn't being translated, see if you can figure out a pattern and then use a regular expression find & replace across all files to fix the problem (Microsoft Visual Studio has a particularly good implementation of this facility). Alternatively, one can use the Unix command grep or even find and simply do a manual one-by-one fix up.

I hope that this helps, and I do apologise for the poor state of translation. In particular I am fairly sure that the lack of translation for "add to cart" was my fault as when I was fixing up the randomly scattered German throughout the UI I didn't do the i18n properly. In the end, I have very little experience with Zope/Plone and sometimes it shows!

(I might add as an aside that I think the translation mechanism used by Zope/Plone sucks - it creates far more work that it ought to. A project I designed myself from scratch called TnFOX can auto-fetch translations from Google Translate which then can be improved if needs be - much easier!)

HTH,
Niall

**Comment by ned14** [comment]
Committed at http://github.com/ned14/Easyshop/commit/ed2f2804a10a68b65735ba899999a6b52a73695f
