### ISSUE TITLE
shipping price question

### ISSUE THREAD

**Issue by kyholdings** [ned14/Easyshop#32]
Hi, 
When I setting the shipping price and payment price, then check in not-logged-in web browser, I find the shipping price is a fixed amount, not multiplied by the weight to get the result. also the payment price also looks like a add-on cost: not multiplied by the goods amount. I think price means multiplier, but when I check the web browser, it looks like only as a cost.
Please help me clear this problem with thanks.

Alex

**Comment by ned14** [comment]
You need to add a criteria to the shipping price, so if weight > 5 and weight < 10 then shipping = X. This is because that's how couriers in Europe at least charge by weight. For the payment price, yes it's a fixed value because again that's how payment processors charge in Europe.

If you want a percentage of the sales value, the easiest is to set it as a sales tax and then hack the text to show "fees" instead of "tax"

**Comment by kyholdings** [comment]
Hi ned14,

It's good suggestion about the fees setting as a percentage.
About the shipping price, it need to add many weight criterias for each 0.5kgs weight increased. Why not works as a price that suit for any weight just only price value multiplied by the goods weight to result the shipping charges?
Is it possable to do like that?
Thanks for your help.

Alex

**Comment by ned14** [comment]
I think you'd need to modify the code to add such a weight based shipping facility. I could be wrong though - best to ask https://groups.google.com/group/easyshop/ and see if anyone answers you.

**Comment by kyholdings** [comment]
Thanks for your suggestion.
I have post my question there but maybe no one will help me to to that: there is long time no post and have many bed post there. no people clean the issues.
I don't know how to modify the code to add such a weight based shipping facility.
Is it possible for you to help me modify such code?

Thanks
Alex

**Comment by ned14** [comment]
Unfortunately that's certainly a day's work for me (you can see my rates at http://www.nedproductions.biz/rates), so at least €500 ex VAT. You could also try petschki (http://github.com/ned14/Easyshop/commits/master?author=petschki) who might be cheaper.

In the end Plone is very much programmer orientated, though it's become much better since Plone v3.x onwards and Plone v5 should make entire product categories like Easyshop obsolete. About time too in my opinion.

**Comment by kyholdings** [comment]
I wonder if the shipping price problem could be solved when Plone V5 issued. Also it will take long time maybe.
Your rate beyond my capacity: it would cost me one month salary。So in this moment, I can only set the criteria step by step. If someone already issued such code, please let me know with thanks.

**Comment by ned14** [comment]
It is not uncommon for someone experienced in Plone to charge US$1000 a day for developing Plone - it is very highly skilled, and there aren't many qualified people. It might worth it for you to try posting a job on guru.com, odesk.com or elance.com and seeing if you can find an Indian or Chinese programmer who could do it. I'd still reckon that US$250 would be the minimum to find someone competent, but you can search guru.com, odesk.com and elance.com for past projects or even google for "plone consulting rates" or something

**Comment by kyholdings** [comment]
Hi ned14,

Now shipping price is a fixed charges against the fixed weight range.
If we can change the shipping cost calculation method as the price multiplied by the weight, it could save me much criteria work. that's what I want it to be now.
So I think the only thing is to change the shipping cost output method in the program.
Is it right?
Alex

**Comment by kyholdings** [comment]
Like DHL in China, send to Europe area, under 10kgs, shipping cost is usd20/kg; 10kg-20kg, usd15/kgs; 20-30kgs, usd12/kg; 30-70kgs, usd10/kgs; more then 70kgs, usd8/kg
So I will simply to add weight criteria 5 times for Europe market if the shipping cost output is shipping price multiplied by weight.
